type FileColorCategory = 'rust' | 'script' | 'frontend' | 'config' | 'docs' | 'media' | 'default';

const EXT_MAP: Record<string, FileColorCategory> = {
  // Rust
  '.rs': 'rust',
  // Script / source code
  '.ts': 'script',
  '.js': 'script',
  '.mjs': 'script',
  '.cjs': 'script',
  '.tsx': 'script',
  '.jsx': 'script',
  '.kt': 'script',
  '.java': 'script',
  '.py': 'script',
  '.rb': 'script',
  '.go': 'script',
  '.c': 'script',
  '.cpp': 'script',
  '.h': 'script',
  '.hpp': 'script',
  '.cs': 'script',
  '.swift': 'script',
  '.lua': 'script',
  '.dart': 'script',
  '.php': 'script',
  '.r': 'script',
  '.sh': 'script',
  '.bash': 'script',
  '.zsh': 'script',
  '.ps1': 'script',
  '.bat': 'script',
  '.cmd': 'script',
  // Frontend / markup
  '.svelte': 'frontend',
  '.html': 'frontend',
  '.css': 'frontend',
  '.scss': 'frontend',
  '.sass': 'frontend',
  '.less': 'frontend',
  '.vue': 'frontend',
  '.astro': 'frontend',
  '.hbs': 'frontend',
  // Config
  '.json': 'config',
  '.toml': 'config',
  '.yaml': 'config',
  '.yml': 'config',
  '.xml': 'config',
  '.lock': 'config',
  '.ini': 'config',
  '.env': 'config',
  '.gradle': 'config',
  '.kts': 'config',
  '.pro': 'config',
  '.properties': 'config',
  '.cfg': 'config',
  '.conf': 'config',
  '.editorconfig': 'config',
  // Docs
  '.md': 'docs',
  '.txt': 'docs',
  '.rst': 'docs',
  '.adoc': 'docs',
  '.log': 'docs',
  // Media / binary
  '.png': 'media',
  '.jpg': 'media',
  '.jpeg': 'media',
  '.gif': 'media',
  '.svg': 'media',
  '.ico': 'media',
  '.webp': 'media',
  '.bmp': 'media',
  '.mp3': 'media',
  '.wav': 'media',
  '.ogg': 'media',
  '.flac': 'media',
  '.mp4': 'media',
  '.avi': 'media',
  '.mov': 'media',
  '.ttf': 'media',
  '.otf': 'media',
  '.woff': 'media',
  '.woff2': 'media',
  '.bin': 'media',
  '.jar': 'media',
  '.aar': 'media',
  '.apk': 'media',
  '.dex': 'media',
  '.so': 'media',
  '.dll': 'media',
  '.exe': 'media',
  '.wasm': 'media',
  '.zip': 'media',
  '.tar': 'media',
  '.gz': 'media',
};

const CATEGORY_CSS: Record<FileColorCategory, string> = {
  rust: 'var(--term-red)',
  script: 'var(--term-blue)',
  frontend: 'var(--term-cyan)',
  config: 'var(--term-purple)',
  docs: 'var(--term-green)',
  media: 'var(--term-white)',
  default: 'var(--amber-faint)',
};

export function fileColor(name: string): string {
  const dot = name.lastIndexOf('.');
  if (dot < 0) return CATEGORY_CSS.default;
  const cat = EXT_MAP[name.slice(dot).toLowerCase()];
  return cat ? CATEGORY_CSS[cat] : CATEGORY_CSS.default;
}
