import type { ITheme } from '@xterm/xterm';

export interface TerminalPalette {
  id: string;
  label: string;
  description: string;
  theme: ITheme;
}

export const PALETTES: TerminalPalette[] = [
  {
    id: 'amber',
    label: 'Amber Classic',
    description: 'Warm amber on matte black — the original CRT',
    theme: {
      background: '#080806',
      foreground: '#FFA826',
      cursor: '#FFC840',
      cursorAccent: '#080806',
      selectionBackground: 'rgba(255, 168, 38, 0.30)',
      black: '#3A3530',
      red: '#FF4848',
      green: '#4FE855',
      yellow: '#FFC840',
      blue: '#6CB6FF',
      magenta: '#C58FFF',
      cyan: '#6FE0E0',
      white: '#E8E4D8',
      brightBlack: '#C49A50',
      brightRed: '#FF6868',
      brightGreen: '#7FFA85',
      brightYellow: '#FFD968',
      brightBlue: '#9CCEFF',
      brightMagenta: '#DAB1FF',
      brightCyan: '#9FF0F0',
      brightWhite: '#FFFAEC',
    },
  },
  {
    id: 'vivid',
    label: 'Vivid',
    description: 'High-contrast bright colors — maximum legibility',
    theme: {
      background: '#0A0A08',
      foreground: '#FFB840',
      cursor: '#FFD060',
      cursorAccent: '#0A0A08',
      selectionBackground: 'rgba(255, 184, 64, 0.35)',
      black: '#2A2520',
      red: '#FF5555',
      green: '#50FA7B',
      yellow: '#F1FA8C',
      blue: '#82AAFF',
      magenta: '#FF79C6',
      cyan: '#8BE9FD',
      white: '#F8F8F2',
      brightBlack: '#D4A050',
      brightRed: '#FF6E6E',
      brightGreen: '#70FF94',
      brightYellow: '#FFFFA5',
      brightBlue: '#A4CCFF',
      brightMagenta: '#FF92D0',
      brightCyan: '#A4F4FF',
      brightWhite: '#FFFFFF',
    },
  },
  {
    id: 'muted',
    label: 'Muted',
    description: 'Softer, desaturated tones — easy on the eyes',
    theme: {
      background: '#0C0C0A',
      foreground: '#C8963A',
      cursor: '#D4A850',
      cursorAccent: '#0C0C0A',
      selectionBackground: 'rgba(200, 150, 58, 0.25)',
      black: '#3A3530',
      red: '#CC5050',
      green: '#5CB868',
      yellow: '#C8A848',
      blue: '#6899CC',
      magenta: '#9978B8',
      cyan: '#5AADAD',
      white: '#B8B4A8',
      brightBlack: '#9A7840',
      brightRed: '#D86868',
      brightGreen: '#78C880',
      brightYellow: '#D4B860',
      brightBlue: '#88B4DD',
      brightMagenta: '#B098CC',
      brightCyan: '#78C4C4',
      brightWhite: '#D4D0C4',
    },
  },
  {
    id: 'phosphor',
    label: 'Phosphor',
    description: 'Green phosphor CRT — retro terminal aesthetic',
    theme: {
      background: '#060806',
      foreground: '#33FF33',
      cursor: '#66FF66',
      cursorAccent: '#060806',
      selectionBackground: 'rgba(51, 255, 51, 0.25)',
      black: '#1A2A1A',
      red: '#FF4848',
      green: '#33FF33',
      yellow: '#CCFF33',
      blue: '#33CCFF',
      magenta: '#CC66FF',
      cyan: '#33FFCC',
      white: '#CCFFCC',
      brightBlack: '#448844',
      brightRed: '#FF6868',
      brightGreen: '#66FF66',
      brightYellow: '#DDFF66',
      brightBlue: '#66DDFF',
      brightMagenta: '#DD88FF',
      brightCyan: '#66FFDD',
      brightWhite: '#EEFFEE',
    },
  },
];

export function getPalette(id: string): TerminalPalette {
  return PALETTES.find(p => p.id === id) ?? PALETTES[0];
}
